name: Build Plugins

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '.github/assets/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '.github/assets/**'
      - '.github/ISSUE_TEMPLATE/**'
jobs:
  prepare:
    if: contains(github.event.head_commit.message, '[ci]') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'Hi3Helper.Hypergryph.Core/**'
              - '.github/workflows/**'
            endfield:
              - 'Hi3Helper.Plugin.Endfield/**'
            arknights:
              - 'Hi3Helper.Plugin.Arknights/**'

      - name: Determine Build Matrix
        id: set-matrix
        run: |
          # retrieve the commit message and pull request title, then normalize both to lowercase to facilitate pattern matching.
          MSG=$(echo "${{ github.event.head_commit.message }} ${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')
          
          # if modified Core，all plugins builds
          if [[ "${{ steps.filter.outputs.core }}" == "true" ]] || [[ "$MSG" == *"(core)"* ]]; then
            echo "Core modified, build all plugins"
            echo 'matrix=["Hi3Helper.Plugin.Endfield", "Hi3Helper.Plugin.Arknights"]' >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # if only modified Endfield
          if [[ "${{ steps.filter.outputs.endfield }}" == "true" ]] || [[ "$MSG" == *"(endfield)"* ]]; then
            echo "only build Endfield。"
            echo 'matrix=["Hi3Helper.Plugin.Endfield"]' >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # if only modified Arknights
          if [[ "${{ steps.filter.outputs.arknights }}" == "true" ]] || [[ "$MSG" == *"(arknights)"* ]]; then
            echo "only build Arknights"
            echo 'matrix=["Hi3Helper.Plugin.Arknights"]' >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "All build"
          echo 'matrix=["Hi3Helper.Plugin.Endfield", "Hi3Helper.Plugin.Arknights"]' >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore and Publish ${{ matrix.plugin }}
        shell: pwsh
        run: |
          dotnet restore ${{ matrix.plugin }}/${{ matrix.plugin }}.csproj `
            -r win-x64

          dotnet publish ${{ matrix.plugin }}/${{ matrix.plugin }}.csproj `
            -c Debug `
            -r win-x64 `
            --self-contained true `
            -p:PublishProfile=DebugNoReflectionPublish `
            --no-restore

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.plugin }}-DebugNoReflectionPublish
          path: |
            ${{ matrix.plugin }}/bin/**/publish/**
